version: '3.4'

services:
  frontproducts:
    image: frontproducts
    ports:
      - 8000:80
    build:
      context: .
      args:
        REACT_APP_API_CATALOGOS: http://localhost:8001/api/Product
        REACT_APP_API_USUARIOS: http://localhost:8002/User
      dockerfile: frontproducts/Dockerfile

  catalogsapi:
    image: ${DOCKER_REGISTRY-}catalogsapi
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: CastalogsAPI/Dockerfile

  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    ports:
      - 8002:80
    build:
      context: .
      dockerfile: UsersAPI/Dockerfile

  