version: '3.4'

services:
  frontproducts:
    image: frontproducts
    ports:
      - 8000:80
    build:
      context: .
      dockerfile: frontproducts/Dockerfile

  catalogsapi:
    image: ${DOCKER_REGISTRY-}catalogsapi
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: CastalogsAPI/Dockerfile

  usersapi:
    image: ${DOCKER_REGISTRY-}usersapi
    ports:
      - 8002:80
    build:
      context: .
      dockerfile: UsersAPI/Dockerfile

  